// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: executable
func (_m *Validator) Validate(executable string) error {
	ret := _m.Called(executable)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(executable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
